version: "2"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/data-love/session-example
  db:
    image: postgres:9.6.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  redis:
    image: redis
    ports:
       - "6379:6379"
